#!/usr/bin/env bash

set -e

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
bin_dir="$script_dir/bin"

source "$script_dir/lib/common.sh"

main() {
    install_bin_dependencies
    configure_bin_path
}

install_bin_dependencies() {
    if command_exists lsof; then
        echo "lsof is already installed"
        return
    fi

    install_package "lsof"
}

configure_bin_path() {
    append_zsh_block "bin" <<EOF
case ":\$PATH:" in
    *":$bin_dir:"*)
        ;;
    *)
        export PATH="$bin_dir:\$PATH"
        ;;
esac
EOF
}

main
