#!/usr/bin/env bash

set -e

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

source "$script_dir/lib/common.sh"

PACKAGES=(
    curl
    wget
    htop
    fzf
    jq
    parallel
    tree
)

main () {
    install_core_packages
}

install_core_packages() {
    install_packages "${PACKAGES[@]}"
}

main
